[package]
name = "webui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
leptos = { version = "0.5.2", features = ["csr"] }
leptos_router = { version = "0.5.2", default-features = false, features = ["csr"] }
leptos_meta = "0.5.2"
common = { path = "../common" }
reqwest = { version = "0.11.22",  features = ["json"] }
serde_json = "1.0.107"

[dev-dependencies]
tokio = { version = "1.33.0", features = ["macros"] }