max_width = 100                         # Maximum width of each line
tab_spaces = 4                          # Number of spaces per tab
indentation_style = "Spaces"            # "Tabs", "Spaces" or "Auto"
newline_style = "Unix"                  # "Unix", "Windows" or "Auto"
attr_value_brace_style = "WhenRequired" # "Always", "AlwaysUnlessLit", "WhenRequired" or "Preserve"
macro_names = ["leptos::view", "view"]  # Macro names which will be formatted
